### ISSUE TITLE
Can't display currencies in full name

### ISSUE THREAD

**Issue by JuliusSaik** [lineofflight/frankfurter#12]
I'm trying to get the currencies to be displayed in full name with the get /currencies method but for some reason it's not working. Maybe I'm typing it wrong?

This is how I do it:
`String url = "https://api.frankfurter.app/latest?currencies&from=USD`

How am I supposed to insert this (I'm coding in java)

**Comment by hakanensari** [comment]
The currency names live at a separate URL: `https://api.frankfurter.app/currencies`

The rates are only returned with the symbols, so you will have to match the data from the two URLs in your code.

**Comment by JuliusSaik** [comment]
thank you!

**Comment by JuliusSaik** [comment]
the app seems to crash when I put different urls in... Any Idea why this happens?

`String url = "https://api.frankfurter.app/latest?from=USD
String url2 = "https://api.frankfurter.app/currencies`

any sample code that you could maybe provide to help me? if no it's ok ill figure it out.

**Comment by JuliusSaik** [comment]
It's saying that a link as `https://api.frankfurter.app/currencies` doesn't exist I tried `https://api.frankfurter.app/latest?currencies` but then it's all the same. The documentation doesn't provide enough info on how to initialize the link or it just plain doesn't work.
