### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by gingerlime** [lineofflight/frankfurter#13]
I've set up some monitoring on the api endpoint at https://api.frankfurter.app/latest?base=usd and it seems down at the moment? also see it on your status page, so I guess you're aware :) but posting just in case

![Screenshot 2020-03-27 at 15 48 26](https://user-images.githubusercontent.com/524274/77768228-761d3700-7042-11ea-88da-e1628cef3550.png)

**Comment by hakanensari** [comment]
@gingerlime thanks for the heads up. Yes, our server crashed; I just fixed it.

**Comment by gingerlime** [comment]
Thank you so much, @hakanensari !

If I spot this in future, shall I report it here? or do you already have monitoring and it's just another hassle to deal with? I obviously don't want to be a burden.

**Comment by hakanensari** [comment]
I do monitor, but I don’t mind an extra ping here, thanks!
