### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by AndreyYarygin** [lineofflight/frankfurter#17]
Hello!

Could you please help me to understand data?

From one point of view i see that you are providing exchange rates for a lot of pairs (like USD/RUB and others):
https://www.frankfurter.app/
From other point of view (if i understand correctly) European Central Bank provides with rates only against EUR:
https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

Could you explain, please, the source of the rates where there is no EUR currency?

Thank you.

**Comment by hakanensari** [comment]
All rates derive from the same EBC dataset. For example `USD/RUB` is calculated based on `USD/EUR` and `RUB/EUR`.

**Comment by AndreyYarygin** [comment]
Hi, Hakan!

Thank you for the answer.

So you have:
* USD/EUR exchange rate from the ECB
* and RUB/EUR exchange rate from the ECB
And from these ones you calculate yourself exchange rate for the USD/RUB and it is **not** exchange rate from the ECB, it is your calculation. Am i correct?

I am asking because there is a difference between official ECB exchange rate and self-calculated. At least for auditors.

**Comment by hakanensari** [comment]
Yes, Frankfurter recalculates based on the original values when you change the base currency.

To be clear, the ECB publishes only euro references rates. You should check with your auditor what they consider acceptable. In Russia, I would assume this would be rates published by their Central Bank?

**Comment by AndreyYarygin** [comment]
Hi, Hakan.

Thank you for the explanation.
We are working in the international company and have companies in different countries.
It may sound strange, but "Big4" auditors are ok with Oanda service where you do not know exactly how rates are calculated ("black box"). Some figures and you should just take on faith them.
https://www.oanda.com/fx-for-business/historical-rates
I do not know now if auditors will be ok with your logic. As for me it is at least clear and transparent.

Thanks again.

Issue could be marked as "Done".
