### ISSUE TITLE
AED currency

### ISSUE THREAD

**Issue by pgdeepak91** [lineofflight/frankfurter#23]
AED currency is widely used. it'll be nice if we add them. Other places it is available but not here.

**Comment by m3nu** [comment]
This project uses ECB data as source. So you would need to ask them to add AED first. 😄

https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

**Comment by reiz** [comment]
Citing from investopedia: 

*"It has been pegged to the United States dollar since 1997 at a rate of 1 U.S dollar to 3.6725 AED."*

That makes 1 AED equal to 0.27229408 USD.
