### ISSUE TITLE
/convert issue

### ISSUE THREAD

**Issue by hunnomad** [lineofflight/frankfurter#29]
Hi All,

I tested your application and found the following. If I call the url with CURL to convert:

`curl https://api.frankfurter.app/latest?amount=1000000&from=GBP&to=USD`

Then I get the following:

`{"amount": 1000000.0, "base": "EUR", "date": "2022-02-21", "rates": {"AUD": 1575100, "BGN": 1955800, "BRL": 5804500, "CAD": 1445400, "CHF": 1038700, "CNY": 7183100, "CZK": 24345000, "DKK": 7439700, "GBP": 832980, "HKD": 8844300, "HRK": 7536000, "HUF ": 357540000," IDR ": 16276340000," ILS ": 3643300," INR ": 84677000," ISK ": 141400000," JPY ": 130200000," KRW ": 1353020000," MXN ": 22995100," MYR ": 4738700, "NOK": 10173800, "NZD": 1687000, "PHP": 58300000, "PLN": 4535100, "RON": 4944800, "RUB": 89086600, "SEK": 10653500, "SGD": 1526500, "THB": 36588000, "TRY": 15468900, "USD": 1133800, "ZAR": 17189500}}`

Meanwhile, the conversion result:

`GBP 10 = USD 13.6114`

What's the problem? Can the base currency be set?

I thank you for your help!

Best regards,
Zsolt from Hungary

**Comment by jlrts** [comment]
Works for me:
```shell
~ % curl "https://api.frankfurter.app/latest?amount=1000000&from=GBP&to=USD"
{"amount":1000000.0,"base":"GBP","date":"2022-03-04","rates":{"USD":1326528}}%
~ %
```
You should quote your URL since there is a `&` which means it will fork the process (I assume you run on a unixy OS)
