### ISSUE TITLE
relation "days" does not exist

### ISSUE THREAD

**Issue by kevinho** [lineofflight/frankfurter#4]
```
 2018-12-07 14:05:23.031 UTC [62] ERROR:  relation "days" does not exist at character 15
db_1   | 2018-12-07 14:05:23.031 UTC [62] STATEMENT:  SELECT * FROM "days" LIMIT 1
web_1  | /usr/local/bundle/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:152:in `async_exec': PG::UndefinedTable: ERROR:  relation "days" does not exist (Sequel::DatabaseError)
web_1  | LINE 1: SELECT * FROM "days" LIMIT 1
web_1  |                       ^
web_1  | 	from /usr/local/bundle/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'

```

**Comment by kevinho** [comment]
i use docker-compose to run this app

**Comment by ahmedakin** [comment]
Same error, Could you solve it?

**Comment by kevinho** [comment]
no

**Comment by ahmedakin** [comment]
I couldnt too,

Do you know how to connect postgresql? Do you know its username and password?

**Comment by archlemon** [comment]
It looks like migrations aren't being run automatically.

I managed to solve/confirm this by running `docker-compose run frankfurter bash` to get into the container, and then run `sequel -m db/migrate postgres://postgres@postgres/postgres` to apply the migrations.

**Comment by hakanensari** [comment]
Apologies for having missed this issue; I just deployed a fix that automates migrations again.
