### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by ChrisJohnson89** [lineofflight/frankfurter#40]
I'm excited about the prospect of integrating your API into my project for use with GPT. To move forward , I'd like to kindly request the creation of a privacy policy page for your API.

I understand that you might already have one in place, so if that's the case, could you please share the link with me?

**Comment by hakanensari** [comment]
I added to the wording in the footnote on the website that the API doesn't track; hope that helps.

**Comment by ChrisJohnson89** [comment]
Thanks!
