### ISSUE TITLE
Can't deploy on Heroku

### ISSUE THREAD

**Issue by Suleman-Elahi** [lineofflight/frankfurter#5]
![image](https://user-images.githubusercontent.com/24384996/51465979-27657480-1d8f-11e9-8d84-76f9bc754dfc.png)

**Comment by hakanensari** [comment]
@Suleman-Elahi, apologies for the late response. This looks like a one-off error with Heroku. I just confirmed that [my test app there runs fine.](http://frankfurter.herokuapp.com/latest)
