### ISSUE TITLE
Same Currency Conversion Returns "Not Found"

### ISSUE THREAD

**Issue by dudi-w** [lineofflight/frankfurter#51]
#### Description:
I encountered an issue with the API when trying to convert the same currency. Specifically, when I send a query to convert EUR to EUR, the API returns a "not found" message instead of the expected conversion rate.
I should mention that I really do sometimes send the same coins for conversion because I don't know which coins are actually fed into my system

#### Steps to Reproduce:
1. Send a GET request to https://api.frankfurter.app/2024-10-02?amount=10&from=EUR&to=EUR.
2. Observe the response.

#### Expected Behavior:
The API should return a response indicating that 1*amount EUR is equal to 1*amount EUR. For example:
```json
{
    "amount": 10,
    "base": "EUR",
    "date": "2024-10-02",
    "rates": {
        "EUR": 10
    }
}
```

#### Actual Behavior:
The API returns the following response:

```json
{
    "message": "not found"
}
```

#### Additional Information:
This behavior is observed across different dates and for different currencies. It seems to be a general issue with handling same-currency conversions.

` Thank you for your attention to this matter. I appreciate the work you are doing with the Frankfurter project and hope this feedback helps improve the API. `

Best regards,
dudi

**Comment by hakanensari** [comment]
@dudi-w Thanks for raising this issue!

Returning the base currency in this edge case feels inconsistent, as we normally exclude it from responses. That said, the **404 Not Found** error is misleading. I’ve made a small change to return a **422** status instead to align with how we handle other invalid inputs (e.g., bad dates, non-positive amounts).

Hope this resolves the issue!
