### ISSUE TITLE
Data not up to date

### ISSUE THREAD

**Issue by Ben-Cliff** [lineofflight/frankfurter#53]
Context:
Querying the latest data should give data of at latest today -1 @16:00. Instead it is currently showing data that is three days late

`https://api.frankfurter.app/latest?from=USD`
Produces
```
{"amount":1.0,"base":"USD","date":"2024-07-26","rates":{"AUD":1.5248,"BGN":1.8009,"BRL":5.6326,"CAD":1.382,"CHF":0.88343,"CNY":7.2514,"CZK":23.361,"DKK":6.8716,"EUR":0.92081,"GBP":0.77696,"HKD":7.8068,"HUF":359.99,"IDR":16293,"ILS":3.6637,"INR":83.75,"ISK":137.85,"JPY":154.55,"KRW":1385.96,"MXN":18.3475,"MYR":4.6575,"NOK":10.9917,"NZD":1.6968,"PHP":58.358,"PLN":3.9355,"RON":4.5781,"SEK":10.8034,"SGD":1.3438,"THB":36.015,"TRY":32.963,"ZAR":18.2432}}
```

Expected Behaviour:
Data is returned from latest today -1 at 16:00 CET

**Comment by hakanensari** [comment]
@Ben-Cliff, updates don't happen exactly at that time. The api polls the data source every 15 minutes, and updates can delay slightly for a variety of reasons.
