### ISSUE TITLE
inconsistent handling of amount=0 depending on the currency

### ISSUE THREAD

**Issue by devYuraKim** [lineofflight/frankfurter#55]
When making requests with amount=0, the response varies depending on the currency specified in the request.

https://api.frankfurter.app/latest?amount=0&from=USD&to=EUR
with the above request, you get the following response 
```
{
  "message": "invalid value for Float(): "NaN""
}
```

https://api.frankfurter.app/latest?amount=0&from=EUR&to=USD
but with this request, everything works out fine
```
{
  "amount": 0,
  "base": "EUR",
  "date": "2024-08-06",
  "rates": {
    "USD": 0
  }
}
```

**Comment by hakanensari** [comment]
@devYuraKim thanks, I figured it's best to use a non-tolerant approach and raise an error in both cases above as well as other non-positive values.
