### ISSUE TITLE
Small mistake in the new page's text for the "latest" endpoint

### ISSUE THREAD

**Issue by maxaltdev** [lineofflight/frankfurter#69]
<img width="559" alt="Screenshot 2024-10-30 023445" src="https://github.com/user-attachments/assets/aa80827b-d44c-44da-865b-19b2cf4fe324">

Seems to be a leftover from the IP-to-country API page :)

**Comment by hakanensari** [comment]
Indeed 😄 

Thanks for the heads-up, fixed!
