### ISSUE TITLE
Inconsistence in responses of endpoints for specific date and for dates range when start date is weekend

### ISSUE THREAD

**Issue by sergey-koryshev** [lineofflight/frankfurter#71]
There is some inconsistence in responses of the following endpoints, for example:

1. https://api.frankfurter.app/2024-11-03
1. https://api.frankfurter.app/2024-11-03..2024-11-04

The first one returns rates for `2024-11-01` which is last work day before `2024-11-03` and this is right data to work with. But second endpoint returns rates only for `2024-11-04` and data for `2024-11-01` is absent. Using rates from `2024-11-01` to exchange prices for date `2024-11-03` is more correctly than using rates from `2024-11-04`.

**Comment by Rolv-Apneseth** [comment]
To add on to this - <https://api.frankfurter.app/2024-11-02..2024-11-03> will just return an error

**Comment by hakanensari** [comment]
Noted, I’ll look at both shortly and get back with an update. Thanks!

**Comment by sergey-koryshev** [comment]
The other interesting case is when start time/end time is Monday and it's today actually. If there is no exchange rate for this date yet, we need to get it from last Friday, but the request will return `not found` error in response. It reproduces on Mondays, for example: https://api.frankfurter.app/2024-11-16..2024-11-18

**Comment by hakanensari** [comment]
This endpoint should now work as expected, thanks for all the input!

**Comment by sergey-koryshev** [comment]
@hakanensari, thank your for the fix! It works as expected now, the issue can be closed I think
