### ISSUE TITLE
CLI and docker compose

### ISSUE THREAD

**Issue by Rolv-Apneseth** [lineofflight/frankfurter#73]
Hey, thanks for making this API.

Just wanted to let you know that I've created [a Rust library and CLI around this API](https://github.com/Rolv-Apneseth/frankfurte-rs), and in doing so I created a `docker-compose` stack for the local testing. Would you be interested in a PR with said `docker-compose.yml` file so that it's easier for users to spin up the API + database with the one command?

**Comment by hakanensari** [comment]
I’ve been considering moving the app to SQLite to keep everything within a single process. In the meantime, yes, sure—thanks!

**Comment by Rolv-Apneseth** [comment]
That might be cool yeah. In the meantime I'll get a quick PR ready when I have a couple minutes.
